### ISSUE TITLE
[Untranslated]: Location - Radisrol

### ISSUE THREAD

**Issue by ZeroTales** [furiousg4m3r/Tales-of-Destiny-DC#1032]
Please describe the location and if it's Day or Night: Day

Please paste or attach a screenshot of the issue.
![image](https://user-images.githubusercontent.com/84109999/118062193-1f3a0480-b39f-11eb-96de-9b3eb661430a.png)
![gsdx_20210513034600](https://user-images.githubusercontent.com/84109999/118062209-27923f80-b39f-11eb-93b7-729d7a127f78.png)

**Comment by AstroZana** [comment]
No longer in Japanese in the repository. Please verify if it's still an issue.
