### ISSUE TITLE
[Proofreading]: Location - Radisrol

### ISSUE THREAD

**Issue by ZeroTales** [furiousg4m3r/Tales-of-Destiny-DC#1035]
Line above screen
![gsdx_20210513040635](https://user-images.githubusercontent.com/84109999/118063077-07fc1680-b3a1-11eb-80ef-842f0adafa7a.png)

Unsure if the issue is from my side or not, but i don't know my way around the emulator settings well enough to check, so submitting this just in case (the previous scene that is similar to this has the same issue)

**Comment by furiousg4m3r** [comment]
I didn't think it would fit but it worked out. Fixed.
![image](https://user-images.githubusercontent.com/77897370/118323262-58bd5d80-b4ce-11eb-8f84-b767d1655f4b.png)
