### ISSUE TITLE
[Proofreading]: Location - Skit in Radisrol

### ISSUE THREAD

**Issue by ZeroTales** [furiousg4m3r/Tales-of-Destiny-DC#1037]
Translation

![gsdx_20210513041407](https://user-images.githubusercontent.com/84109999/118064226-4b578480-b3a3-11eb-9e3f-16e2ab46db21.png)

Wouldn't something like "That man followed us on his own....well, I'm glad he's helpful" be more accurate?

**Comment by AstroZana** [comment]
Updated the line to be more in line with the original Japanese:

That guy would come and go as he pleased.
...Well, at least he was helpful.
