### ISSUE TITLE
[Proofreading]: Location - Mikheil

### ISSUE THREAD

**Issue by Apollo326** [furiousg4m3r/Tales-of-Destiny-DC#1040]
Please describe correction needed:

"Such a me could be a weakness for that person"
Maybe
"I can become a weakness for that person"
or even change that person to Leon, but that isn't nessassary

Please paste or attach a screenshot of the issue.
![image](https://user-images.githubusercontent.com/84112079/118067508-15041000-b377-11eb-9430-4d310fdcb2d7.png)

**Comment by furiousg4m3r** [comment]
Replaced with "I was always a weakness for him."
