### ISSUE TITLE
[Untranslated]: Location - ALL SYNOPSIS IN SAVE/LOAD MENU

### ISSUE THREAD

**Issue by LV99VIVI** [furiousg4m3r/Tales-of-Destiny-DC#1048]
When you go to load a file and hit the synopsis button it comes up all japanese, an easy place to miss but for itd be pretty helpful at times to have translated

![Screenshot 2021-05-13 195809](https://user-images.githubusercontent.com/75486703/118201566-c19ccb00-b425-11eb-83b0-95e9f16c0611.png)
![Screenshot 2021-05-13 195831](https://user-images.githubusercontent.com/75486703/118201570-c3668e80-b425-11eb-9717-9d0deb7cccb8.png)

**Comment by AstroZana** [comment]
We are working on translating all synopsis and inserting it into the game.

**Comment by LV99VIVI** [comment]
nice just making sure it makes me cry im going to be able to play this game in english in my lifetime

**Comment by AstroZana** [comment]
same! we are really excited to get this to everyone. I think we're at the point where we need it insert the translation into the game and see if it breaks. Stay tuned!
