### ISSUE TITLE
[Proofreading]: Location - Item Description

### ISSUE THREAD

**Issue by ZeroTales** [furiousg4m3r/Tales-of-Destiny-DC#1058]
Item Description

![gsdx_20210514130122](https://user-images.githubusercontent.com/84109999/118342796-afa64f80-b52d-11eb-8bc6-5dfce4b86831.png)

after my previous report on this item, it was reworded, but the issue still remains, it is not explaining the side effect of using Demon Gem

**Comment by xsonicdragon** [comment]
The original translation keeps it ambiguous for the players to find out.
