### ISSUE TITLE
Next updates

### ISSUE THREAD

**Issue by MediaMaquina** [furiousg4m3r/Tales-of-Destiny-DC#1065]
Hi, i've got a question. Are you planning to keep releasing mini-updates every 12 hs or are you maybe planning to release a version 1.0 and then, get all reports and do a 1.1 in a month? I suggest this because re-patching every 12 hs to get fixes gets tiresome. Maybe do a release schedule every-- weeks/months?

**Comment by furiousg4m3r** [comment]
We are still in BETA, pre version1.0. There will continue to be daily updates until we hit v1.0. At that point I see us releasing less frequent patches. But 1.0 will happen once we get all the menu done.

**Comment by MediaMaquina** [comment]
Gotcha thanks!
