### ISSUE TITLE
[Proofreading]: Location - Frostheim

### ISSUE THREAD

**Issue by talesofphatnastia** [furiousg4m3r/Tales-of-Destiny-DC#1093]
Please describe correction needed: Location name in the title of skits is different from the content of the skit. Maybe change Tyrso to Tilso to stay consistent with the World Map.

Please paste or attach a screenshot of the issue.
![gsdx_20210517180743](https://user-images.githubusercontent.com/83388522/118562845-7d6a3d00-b73b-11eb-9194-ab988e9246b1.png)
![gsdx_20210517180806](https://user-images.githubusercontent.com/83388522/118562895-95da5780-b73b-11eb-8a7e-00fc7fd789ca.png)

**Comment by furiousg4m3r** [comment]
This has been fixed.
