### ISSUE TITLE
[Proofreading]: Darilsheid - Before Leon join the party

### ISSUE THREAD

**Issue by NihilesMann** [furiousg4m3r/Tales-of-Destiny-DC#1099]
![gsdx_20210518225924](https://user-images.githubusercontent.com/84419193/118724551-07df9900-b82f-11eb-8299-e9cdd0635bdf.png)
Please describe correction needed:
Sorry for my bad English, I think the line should start with "Well" and not "Weld"
Please paste or attach a screenshot of the issue.

**Comment by furiousg4m3r** [comment]
It actually says "Welp". Which is a nonstandard spelling of "well", representing an informal pronunciation (typically used to convey resignation or disappointment). Thanks for submitting the issue.
