### ISSUE TITLE
[Proofreading]: Location - Neustadt

### ISSUE THREAD

**Issue by NihilesMann** [furiousg4m3r/Tales-of-Destiny-DC#1123]
![gsdx_20210521000626](https://user-images.githubusercontent.com/84419193/119148563-e52acb80-ba4c-11eb-8d85-76d02e410533.png)
As always, sorry for my bad english. In the house near the one you left Leon for the Ice Cream, there are 2 Twins called "Things", I think the right translation is "Twin 1" and "Twin 2"

**Comment by AstroZana** [comment]
Thing 1 and Thing 2 is an Easter egg. It references Dr. Suess' characters from the Cat in the Hat book. It was done intentionally as a joke. More information about Thing 1 and Thing 2 can be found here:

https://seuss.fandom.com/wiki/Thing_One_and_Thing_Two
