### ISSUE TITLE
[Untranslated]: Location - Sunken Ship

### ISSUE THREAD

**Issue by ZeroTales** [furiousg4m3r/Tales-of-Destiny-DC#1126]
Monster Arte

![gsdx_20210522011434](https://user-images.githubusercontent.com/84109999/119221554-9c305100-baf8-11eb-92ea-e078eaaf3b99.png)
![gsdx_20210522010733](https://user-images.githubusercontent.com/84109999/119221564-a3575f00-baf8-11eb-8736-764d6eac4a90.png)

**Comment by furiousg4m3r** [comment]
Made the hex change in the enemy files. Should be good in the next patch.
