### ISSUE TITLE
[Proofreading]: Location - 

### ISSUE THREAD

**Issue by godreborn** [furiousg4m3r/Tales-of-Destiny-DC#1136]
I wasn't sure if this was a bug issue or a proofreading issue, so I put it here.  the game doesn't crash, but the text box when you first load up the game (if you don't have enough space on the memory card) isn't sized correctly.  it cuts off part of the text:

![DZKKnug](https://user-images.githubusercontent.com/13548481/119685263-d193b200-be0a-11eb-8f05-a7770fd13d1a.jpg)

**Comment by furiousg4m3r** [comment]
Fixed. Will appear in the next patch.
![image](https://user-images.githubusercontent.com/77897370/119744571-4f32de80-be5a-11eb-99d4-f04415b11320.png)
