### ISSUE TITLE
[Proofreading]: Location - Darilsheid Cutscene - After Draconis crash/landing

### ISSUE THREAD

**Issue by NihilesMann** [furiousg4m3r/Tales-of-Destiny-DC#1153]
Please describe correction needed:During the cutscene all 3lines-texts are not centered. Some examples
![gsdx_20210603150821](https://user-images.githubusercontent.com/84419193/120652863-756f0480-c480-11eb-8eaf-48980aaeeb96.png)
![gsdx_20210603150827](https://user-images.githubusercontent.com/84419193/120652872-76a03180-c480-11eb-87c0-de14ce1976d9.png)
![gsdx_20210603150847](https://user-images.githubusercontent.com/84419193/120652877-7738c800-c480-11eb-8f89-f268b74b5965.png)

Please paste or attach a screenshot of the issue.

**Comment by furiousg4m3r** [comment]
All of these have been fixed. Will be good in next patch.
