### ISSUE TITLE
[Untranslated]: Location - Final Dungeon (?)

### ISSUE THREAD

**Issue by NihilesMann** [furiousg4m3r/Tales-of-Destiny-DC#1156]
Please describe the location and if it's Day or Night:
As always, sorry for my bad english, In the final Dungeon (?) (The caste with mirrors that you reach after the laser-cannon shoot and the draconis repair) after you arrive the first save (I think) and the teleporter that brng you back to the entrance there is another teleporter that brings you to a sort of purple/crystal cave, on the right there is a mirror, passing in front of it started the battle (this enemy is not presented in the bestiary). 
Please paste or attach a screenshot of the issue.
![gsdx_20210607235344](https://user-images.githubusercontent.com/84419193/121092802-6bd0fe00-c7ec-11eb-9df7-a545323d9803.png)
![gsdx_20210607235523](https://user-images.githubusercontent.com/84419193/121092807-6e335800-c7ec-11eb-8b76-945bbb19d9cf.png)

**Comment by NihilesMann** [comment]
In the same area, after the party split in half there is a similar problem with Woodrow's replica
![gsdx_20210608002002](https://user-images.githubusercontent.com/84419193/121094848-8bb5f100-c7ef-11eb-9f36-39adcea872f9.png)

**Comment by furiousg4m3r** [comment]
Fixed in V0.0.207
