### ISSUE TITLE
"Visiting Multiple Countries" skit

### ISSUE THREAD

**Issue by almightycinder** [furiousg4m3r/Tales-of-Destiny-DC#1165]
Not really sure what it is, but something seems odd about this skit. It's right before you enter Shiden.

Stahn: I never thought I would visit so many different countries in such a short time.
Rutee: You were going to be a knight in Seinegald, right?
Dymlos: I'm treated as a bad guy now.
Stahn: Oh, I don't think so.
Rutee: Did you forget? Why don't you ask Leon to remind you with an electric shock?

It feels like some soft of context is missing from one of the lines. Dymlos's line does not feel like it matches up with the first two lines.

**Comment by AstroZana** [comment]
You are correct. Japanese doesn't indicate subject 90% of the time so it was translated as "I" instead of "We" or "You" for Dymlos' line. It now reads "Now you are being treated like a criminal" Thanks for the report.
