### ISSUE TITLE
[Proofreading]: Location - Moreau skit

### ISSUE THREAD

**Issue by almightycinder** [furiousg4m3r/Tales-of-Destiny-DC#1170]
Please describe correction needed: I believe in this context, it should be spelled "aides". There's several conversations before this line that also spelled it "aides".

Please paste or attach a screensh
![aides](https://user-images.githubusercontent.com/85787194/122031475-99392100-cd83-11eb-8db4-c4f6b9ebee5c.png)
ot of the issue.

**Comment by AstroZana** [comment]
This has been fixed and should be correct in the most recent patch.
