### ISSUE TITLE
"Cyril's to the North" skit

### ISSUE THREAD

**Issue by almightycinder** [furiousg4m3r/Tales-of-Destiny-DC#1175]
![cyril](https://user-images.githubusercontent.com/85787194/122370165-b6045e80-cf13-11eb-8bae-414f8c9f9a1d.png)
Title of skit is wrong, Woodrow's line is correct. We're in Cyril.

**Comment by AstroZana** [comment]
Nice catch - the Japanese for reference サイリルから北へ which translates to "To the North from Cyril."
