### ISSUE TITLE
[Proofreading]: Phandaria Pass - Criticals Hurt! tutorial needs line breaks

### ISSUE THREAD

**Issue by orbea** [furiousg4m3r/Tales-of-Destiny-DC#1718]
version: `0.0.235`
![ToD_long_text](https://user-images.githubusercontent.com/4204285/182222592-830987ab-5090-480c-a692-e86a6a9f1769.png)

Early in the game when in Phandaria Pass before reaching Janos the text for the `Critical's Hurt!` tutorial is too long and needs some line breaks.

**Comment by Fis-Ura** [comment]
done
