### ISSUE TITLE
[Proofreading]: Harmentz - Blast Caliber tutorial needs line break

### ISSUE THREAD

**Issue by orbea** [furiousg4m3r/Tales-of-Destiny-DC#1723]
version: `0.0.235`
![ToD_blast_caliber_harmentz](https://user-images.githubusercontent.com/4204285/182934659-3a79dc6b-71bd-466f-ad87-08559621edf7.png)

The text for the `Blast Caliber` tutorial in Harmentz during the fight against the knights is slightly too long.

**Comment by Fis-Ura** [comment]
done
