### ISSUE TITLE
[Proofreading]: Menu - Broken line break in the Elder Cloak description

### ISSUE THREAD

**Issue by orbea** [furiousg4m3r/Tales-of-Destiny-DC#1724]
version: `0.0.236`

There is an errant `[Line[` in the description of the `Elder Cloak` in Rutee's equipment menu . The `Elder Robe` in Philia's menu doesn't have this issue even with the nearly identical description.

![ToD_Elder_Cloak_Rutee](https://user-images.githubusercontent.com/4204285/183309579-928e7523-3f2b-43b6-a6ba-a80430f33c39.png)
![ToD_Elder_Robe_Philia](https://user-images.githubusercontent.com/4204285/183309582-33070de6-4a07-4451-a23e-94ef4399d605.png)

**Comment by Fis-Ura** [comment]
done
