### ISSUE TITLE
[Proofreading]: Menu - Inconsistent spacing between % and HP 

### ISSUE THREAD

**Issue by orbea** [furiousg4m3r/Tales-of-Destiny-DC#1726]
In the main menu there is inconsistent spacing between the `%` symbol and `HP`. Some places have `%HP` and others have `% HP`.  For example `10%HP` and `10% HP`. I'm not sure which is preferred, but they should be at least inconsistent. Personally I think they should have a space between `%` and `HP` as shown in the third image, it looks better.
![ToD_Menu_HP_1](https://user-images.githubusercontent.com/4204285/183577567-2ca1dbd6-54e9-402a-8f5e-b9d48d5ef622.png)
![ToD_Menu_HP_2](https://user-images.githubusercontent.com/4204285/183577569-aea66a18-d5fc-4a28-881f-6ff563123c07.png)
![ToD_Menu_HP_3](https://user-images.githubusercontent.com/4204285/183577573-df34ec45-d8ad-4a99-9ebf-dcf336c1f46e.png)

**Comment by Fis-Ura** [comment]
fixed thanks for the report
