### ISSUE TITLE
Typo in the "Changing characters" tutorial

### ISSUE THREAD

**Issue by Floflo81** [furiousg4m3r/Tales-of-Destiny-DC#1740]
See the following screenshot:
![gsdx_20220821204956](https://user-images.githubusercontent.com/9168392/185806788-7a9e5ec8-c433-4834-8fd4-d52e5fde053c.jpg)

~~The line before the last starts with "to the top." But it's repeated from the previous line!~~
~~The second "to the top." should be removed.~~

Edit: After rereading the screenshot, actually there is more text than that that is repeated 😅
The following line should simply be removed in its entirety:
"the character you want to control to the top."
Part of it is already on the previous line and on the next line

Using the 0.0.238 patch with PCSX2.

Thanks for this fan translation that looks really professional. 😃

**Comment by Floflo81** [comment]
Also, I'm not really sure what the last sentence "You may find new combat skills" means in this context.
But maybe it's the same in the original Japanese?

**Comment by Fis-Ura** [comment]
Thanks you for the report the fix is done and should be in the next patch
