### ISSUE TITLE
[Proofreading]: Location - Tilso Forest

### ISSUE THREAD

**Issue by ichronox** [furiousg4m3r/Tales-of-Destiny-DC#1741]
Please describe correction needed: Line break while opening a chest on Tilso Forest which contains Enduro Fruit.

Please paste or attach a screenshot of the issue:
![TaD-DC](https://user-images.githubusercontent.com/53710589/185837004-8b3436cf-8eb1-45e7-9146-a223c30a777d.png)

Using the 0.0.238 patch with PCSX2. (Latest nightly 1.7 build as of Aug 21 2022)

**Comment by Fis-Ura** [comment]
thanks for the report, the fix is done and will be in the next patch
