### ISSUE TITLE
Rutee joining freeze

### ISSUE THREAD

**Issue by Lightplol** [furiousg4m3r/Tales-of-Destiny-DC#186]
When freeing Rutee from the temple and after joining your party, the game freezes where the screenshot shows.
![pcsx2_2021-02-05_07-06-47](https://user-images.githubusercontent.com/78600503/107037251-cef04c80-6788-11eb-8308-2f8cb0635ccb.jpg)

**Comment by pnvnd** [comment]
13658_85.txt

**Comment by pnvnd** [comment]
Reduced text by finding `<__><00>` and replacing with `<00>`.  This allows the "notice" to show up, but freeze after.
![image](https://user-images.githubusercontent.com/65086728/107901813-9b44bd80-6f12-11eb-911b-945b6b97506b.png)

**Comment by FistingUranus** [comment]
Solved and fixed
