### ISSUE TITLE
Seinegald Castle Freeze

### ISSUE THREAD

**Issue by pnvnd** [furiousg4m3r/Tales-of-Destiny-DC#200]
Seinegald Castle freeze.  Fix Stahn side, break Leon side, vice versa.  Might be related to text length.
![leon_error](https://user-images.githubusercontent.com/65086728/107107665-92603780-6800-11eb-9a86-7496d70417b5.png)

**Comment by Goodguy3** [comment]
[LeonsideHugoFreeze1.zip](https://github.com/pnvnd/Tales-of-Destiny-DC/files/5976003/LeonsideHugoFreeze1.zip)
Here is a memory card containing the save for this freeze. Please load the save, and then enter Seinegald Castle. The Scene will play out. Please note that the freeze spot is slightly different now.

**Comment by pnvnd** [comment]
Reducing English text will let the story proceed further.  If the story text is short enough, it will work on Leon side, but break on Stahn's side.

**Comment by pnvnd** [comment]
13691_72.txt

**Comment by pnvnd** [comment]
Fixing Leon's side breaks Stahn's side
![image](https://user-images.githubusercontent.com/65086728/107964020-e1336d00-6f76-11eb-9410-163d92c142c5.png)

**Comment by Goodguy3** [comment]
Hmmmm....does it have to be exactly the same character amount as the Japanese version of the original file?

**Comment by furiousg4m3r** [comment]
Freezing fixed by keep bytes at 4096.

**Comment by furiousg4m3r** [comment]
Freezing fixed by keep bytes at 4096.
