### ISSUE TITLE
Marian Scene Freeze, File 13735_49

### ISSUE THREAD

**Issue by Goodguy3** [furiousg4m3r/Tales-of-Destiny-DC#202]
Upon completing the first time you go to Straylize Temple, after going to the Harbor in Darilshied, and after Leon reports that they need a boat to both Hugo and the King, Leon decides to go see Marian one more time before heading to Calvalese.

There, a scene is supposed to play out where the two have a little heart-to-heart. 

Unfortunately, Marian gets stuck in this pose here:
![image](https://user-images.githubusercontent.com/77896919/107119209-227b9c80-6854-11eb-8554-7681c27df251.png)

This is also not an event that you can skip.

This file does have another scene shared by both Stahn and Leon's sides which I have translated. The dialogue for this scene in this issue has not yet been translated, and begins on Line 296. It does not appear that any of it gets skipped.

**Comment by Goodguy3** [comment]
An update, the game now freezes after this dialogue:

![image](https://user-images.githubusercontent.com/77896919/107839885-bf6e9600-6d7c-11eb-8ab6-420a90ab6d65.png)

Leaving them in this pose 

![image](https://user-images.githubusercontent.com/77896919/107839889-c9909480-6d7c-11eb-8155-3a04cdb0f16c.png)

The music still plays during this. Unlike other freezes like this, you cannot soft-reset or even pause during this freeze. I do not know the cause of this one, at all.

Here is what the log looks like during this "freeze".


![image](https://user-images.githubusercontent.com/77896919/107839912-f9d83300-6d7c-11eb-9e4b-77bdd6876f71.png)
it seems to continue reading memory, no obvious errors seem to be occuring.

**Comment by Goodguy3** [comment]
[LeonSideMarianFreeze.zip](https://github.com/pnvnd/Tales-of-Destiny-DC/files/5976017/LeonSideMarianFreeze.zip)
Here is a memory card containing a save as close to this event as is possible. Please load the save, exit the Inn, and then either go Right then Up, or Up then Right, and then enter the manor. The scene will play out as described above.

**Comment by dawnbomb** [comment]
Confirming the freeze. Also the screen minorly violently vibrates all over the place to show how angry it is that it crashed.
