### ISSUE TITLE
Rutee's Greedy Witch event freezes

### ISSUE THREAD

**Issue by Lightplol** [furiousg4m3r/Tales-of-Destiny-DC#212]
After choosing the first option in Rutee's Greedy Witch (Rutee's title that you get in front of the Darilsheid castle) event I get a black screen+freeze.

**Comment by furiousg4m3r** [comment]
Fixed with utf8 version of file. Will be included in the next patch.

**Comment by furiousg4m3r** [comment]
Fixed with utf8 version of file. Will be included in the next patch.
