### ISSUE TITLE
Rutee Neat Sister title freeze

### ISSUE THREAD

**Issue by Lightplol** [furiousg4m3r/Tales-of-Destiny-DC#296]
In Shiden, right before acquiring Rutee's ''Neat Sister'' title, the game crashes. 
![pcsx2_2021-02-12_14-50-58](https://user-images.githubusercontent.com/78600503/107815841-ebb8f100-6d41-11eb-815c-bcffa9a94e8e.png)

**Comment by pnvnd** [comment]
On another note, need to find graphics on left "出口" and edit to "exit".

**Comment by FistingUranus** [comment]
14064_69.txt  should be this file
