### ISSUE TITLE
Philia Joining Bug

### ISSUE THREAD

**Issue by Goodguy3** [furiousg4m3r/Tales-of-Destiny-DC#302]
Thankfully not a freeze, but when Philia joins the party it skips quite a bit of dialogue. Here's a video of it:

https://www.youtube.com/watch?v=cEi6aY5ALoI&feature=youtu.be

This was recorded on Leon's side. Don't know if this happens on Stahn's side, but since this event is the same regardless of which side is being played, it is extremely likely.

**Comment by Goodguy3** [comment]
[EitherSidePhiliaBug.zip](https://github.com/pnvnd/Tales-of-Destiny-DC/files/5976023/EitherSidePhiliaBug.zip)
Here is a memory card containing a save as close to this event as is possible. Simply load the save from the memory card and then go through the opened door.

**Comment by pnvnd** [comment]
@Goodguy3 Can you add the file name?  Thanks!

**Comment by furiousg4m3r** [comment]
Fixed in patch v0.0.135.
