### ISSUE TITLE
Janos Inn not working

### ISSUE THREAD

**Issue by 0Chirri** [furiousg4m3r/Tales-of-Destiny-DC#375]
It seems no one posted this bug before so i'll do it.

![image](https://user-images.githubusercontent.com/79593662/109031328-e99d4d80-76c4-11eb-93a2-b3aa8b32050f.png)

When you talk to the inkeeper, if you select "yes" to stay at the inn, nothing will happend and the result is the same as selecting "no"

![image](https://user-images.githubusercontent.com/79593662/109032206-b909e380-76c5-11eb-9fa0-8665dbb80f98.png)

Also the PCSX2 emulator show those red warnings of missing some TBL. Not a game freezing bug though.

**Comment by furiousg4m3r** [comment]
Fixed in patch v0.0.135.
