### ISSUE TITLE
Neuestadt Race event glitch

### ISSUE THREAD

**Issue by furiousg4m3r** [furiousg4m3r/Tales-of-Destiny-DC#384]
Race boy gets stuck even when file is reverted to original.

![image](https://user-images.githubusercontent.com/77897370/109409250-271d0780-795f-11eb-87ac-fc25e86bc9a2.png)

**Comment by pnvnd** [comment]
Don't include the MGLK file from this scene to revert back.  Fix to come...eventually.

**Comment by FistingUranus** [comment]
file 13986_61 or 14008_54

**Comment by FistingUranus** [comment]
Still softlock patch 00147
