### ISSUE TITLE
Game freeze on skit

### ISSUE THREAD

**Issue by Lightplol** [furiousg4m3r/Tales-of-Destiny-DC#444]
Game freeze when opening this skit 

![image](https://user-images.githubusercontent.com/78600503/111238298-2fb34600-85cd-11eb-8c74-ea1e2c9520c7.png)

**Comment by 0Chirri** [comment]
Thank you Lightplol ^^

**Comment by furiousg4m3r** [comment]
Fixed by leaving some lines in Japanese. Will be in next patch.
![image](https://user-images.githubusercontent.com/77897370/111911725-17b04c00-8a3d-11eb-83ee-d114c032d95a.png)

**Comment by furiousg4m3r** [comment]
Fixed in patch v0.0.144.
