### ISSUE TITLE
Cherik - Baruk's office 13930_55.txt Softlock patch00141

### ISSUE THREAD

**Issue by FistingUranus** [furiousg4m3r/Tales-of-Destiny-DC#460]
![image](https://user-images.githubusercontent.com/77898683/111739290-30f8a300-8859-11eb-90d8-fa4102e1e400.png)

**Comment by furiousg4m3r** [comment]
Fixed. Will be in the next release.
![image](https://user-images.githubusercontent.com/77897370/111795984-1694e880-889e-11eb-8d34-4c948f0c8f32.png)
