### ISSUE TITLE
Cherik - Shop District - 13925_36.txt Merchant Crash 

### ISSUE THREAD

**Issue by FistingUranus** [furiousg4m3r/Tales-of-Destiny-DC#461]
![image](https://user-images.githubusercontent.com/77898683/111739454-73ba7b00-8859-11eb-97d2-32681358b71e.png)

**Comment by FistingUranus** [comment]
did not crash in storypatch 00134

**Comment by furiousg4m3r** [comment]
Fixed! Will release in next patch.
![image](https://user-images.githubusercontent.com/77897370/111784309-ac764680-8891-11eb-8b2b-cea032655dc6.png)
