### ISSUE TITLE
Harmentz "voiceless" woman

### ISSUE THREAD

**Issue by 0Chirri** [furiousg4m3r/Tales-of-Destiny-DC#473]
![image](https://user-images.githubusercontent.com/79593662/111890888-199eee80-89ee-11eb-8947-c3d35f0f3541.png)
Dialogue won't show up when talking to this woman

**Comment by furiousg4m3r** [comment]
Fixed. Will be released in next patch.

**Comment by furiousg4m3r** [comment]
Released in v0.0.148.
