### ISSUE TITLE
Radisrol Bug patch 00143 13887_73.txt

### ISSUE THREAD

**Issue by FistingUranus** [furiousg4m3r/Tales-of-Destiny-DC#475]
![image](https://user-images.githubusercontent.com/77898683/111892881-9e314300-89d5-11eb-9f13-e2bce387da63.png)

Trying ot leave this room load you back into the same room on radisrol now. this is when you try to access the room with the electric wall, it teleport you to a chest room that you are unable to leave

**Comment by FistingUranus** [comment]
![image](https://user-images.githubusercontent.com/77898683/111892999-2adc0100-89d6-11eb-9fb4-3ae2d6e4431b.png)
Same with another room with a chest

**Comment by FistingUranus** [comment]
![image](https://user-images.githubusercontent.com/77898683/111893488-67f5c280-89d9-11eb-8dbf-175a1af9e5a7.png)
I tried all the 3 entrance to that room and got warp to the location in the red square the broken file is 

13887_73.txt | Radisrol - Opening Doors

**Comment by furiousg4m3r** [comment]
Fixed in Patch v0.0.144
