### ISSUE TITLE
Young boy in Darilsheid

### ISSUE THREAD

**Issue by 0Chirri** [furiousg4m3r/Tales-of-Destiny-DC#515]
![calle posada npc](https://user-images.githubusercontent.com/79593662/112707729-a8f44800-8ead-11eb-83c9-340bab92a9ad.png)

**Comment by FistingUranus** [comment]
file 13721_77, no [ENDBLOCK] missing and the text is in the 4096 range, probably too much text that break the pointers

**Comment by FistingUranus** [comment]
seems to be fix in patch 00150

**Comment by furiousg4m3r** [comment]
![image](https://user-images.githubusercontent.com/77897370/112776748-7ada4980-900e-11eb-9265-474a3c9e4a33.png)
Fixed in patch v0.0.151.
