### ISSUE TITLE
Rutee title in Darilsheid Softlock

### ISSUE THREAD

**Issue by 0Chirri** [furiousg4m3r/Tales-of-Destiny-DC#516]
2 isues with this guy
![image](https://user-images.githubusercontent.com/79593662/112707997-9549e100-8eaf-11eb-8dc1-ca79e81829b7.png)
First:
![image](https://user-images.githubusercontent.com/79593662/112708045-e3f77b00-8eaf-11eb-810c-8f22009acec0.png)
and it softlock at this part:
![image](https://user-images.githubusercontent.com/79593662/112708055-fc679580-8eaf-11eb-8d4e-98d195a3bfcc.png)

**Comment by FistingUranus** [comment]
False positive line file 13690_59, i applied the fix well need to check if it's still there

**Comment by FistingUranus** [comment]
![image](https://user-images.githubusercontent.com/77898683/112708468-8865c700-8e88-11eb-8028-b1913190799e.png)

**Comment by furiousg4m3r** [comment]
Fixed in patch v0.0.151.
