### ISSUE TITLE
Exiting the Kalviola inn at night crash the game

### ISSUE THREAD

**Issue by 0Chirri** [furiousg4m3r/Tales-of-Destiny-DC#524]
![image](https://user-images.githubusercontent.com/79593662/112738774-4f9c1f80-8f66-11eb-8614-483cb87eb02a.png)

**Comment by FistingUranus** [comment]
13957_43

**Comment by FistingUranus** [comment]
ITS FIXED:)

**Comment by furiousg4m3r** [comment]
Fixed in patch v0.0.151.
