### ISSUE TITLE
Emulator crash after this scene (Waltz house)

### ISSUE THREAD

**Issue by Lightplol** [furiousg4m3r/Tales-of-Destiny-DC#544]
![image](https://user-images.githubusercontent.com/78600503/112932137-661fb380-90eb-11eb-89ee-4950b1cb5398.png)

**Comment by furiousg4m3r** [comment]
![image](https://user-images.githubusercontent.com/77897370/113075827-beae8980-919b-11eb-94c2-ce1eb7d48e14.png)
Fixed in v0.0.153.
