### ISSUE TITLE
Moreau Bug

### ISSUE THREAD

**Issue by WishesDoDishes** [furiousg4m3r/Tales-of-Destiny-DC#607]
With newest patch 0.0.159 I am encountering a bug when entering Moreau, or loading a save from within the town, that causes an encounter with two wolves (rarely a single wolf or wyvern) to initiate and crashes the game.
Tested Japanese ISO and was fine. Re-patched and tried the previous patch version I was using (0.0.151), and the problem was not present.
Used a clean iso for the new patch.

UPDATE: Tested on version 0.0.158 and the bug was not present there either. Appears to be new to 159.

Below is my error log.
Appreciate all your work.
![image](https://user-images.githubusercontent.com/82054916/113762619-c5cb1f80-96e6-11eb-804a-d1bd78f33985.png)

**Comment by furiousg4m3r** [comment]
Fixed in patch v0.0.160
