### ISSUE TITLE
[Proofreading]: Junkland - Young Person

### ISSUE THREAD

**Issue by furiousg4m3r** [furiousg4m3r/Tales-of-Destiny-DC#727]
Please describe correction needed: Refine verbage. And translate Gald line.

![image](https://user-images.githubusercontent.com/77897370/116011248-fde0c680-a5f1-11eb-9c65-88a84824f2d4.png)

Please paste or attach a screenshot of the issue.

**Comment by furiousg4m3r** [comment]
Gald line has been translated. Not sure it the other really needs tweaked.

**Comment by FistingUranus** [comment]
Junktown rewording #1023
Fixed for a better line
Buy 3 for 120 Gald?
