### ISSUE TITLE
[Proofreading]: Lumina Draconis 

### ISSUE THREAD

**Issue by furiousg4m3r** [furiousg4m3r/Tales-of-Destiny-DC#735]
Please describe correction needed: "so please go to the castle."

Please paste or attach a screenshot of the issue.

![image](https://user-images.githubusercontent.com/77897370/116081651-8601b300-a668-11eb-92f6-ff7a8be58571.png)

**Comment by FistingUranus** [comment]
Fixed with recomended sentence 13574_78 line 94

Also, <Reynolds> has a message
for you. He wants to talk to you,
so please go to the castle.
