### ISSUE TITLE
[Proofreading]: Draconis - Bridge

### ISSUE THREAD

**Issue by furiousg4m3r** [furiousg4m3r/Tales-of-Destiny-DC#739]
Please describe correction needed: 
Even with so little, I think I can still fix the Draconis.

Please paste or attach a screenshot of the issue.
![image](https://user-images.githubusercontent.com/77897370/116157261-ab1f1180-a6ba-11eb-872b-5469c5be4664.png)

**Comment by FistingUranus** [comment]
fixed with recommended sentence  13574_78 line 72
