### ISSUE TITLE
[Proofreading]: Darilsheid Castle Exterior - Lens Cannon

### ISSUE THREAD

**Issue by furiousg4m3r** [furiousg4m3r/Tales-of-Destiny-DC#742]
Please describe correction needed:
Dialogue box starts to run offscreen. Insert linebreak.

Please paste or attach a screenshot of the issue.
![image](https://user-images.githubusercontent.com/77897370/116239099-41d9e580-a730-11eb-98f0-bdd924696f24.png)

**Comment by FistingUranus** [comment]
Fixed
