### ISSUE TITLE
[Untranslated]: Dycroft - Stahn Doppleganger

### ISSUE THREAD

**Issue by furiousg4m3r** [furiousg4m3r/Tales-of-Destiny-DC#748]
Please describe the location and if it's Day or Night:
In Dycroft near the end of the game. Enemy name not translated.

Please paste or attach a screenshot of the issue.
![image](https://user-images.githubusercontent.com/77897370/116315804-074b6980-a77f-11eb-9f67-e66676f8dd62.png)

**Comment by FistingUranus** [comment]
I believe this is link to the save, and that new saves with edited name will not show this in japanese

**Comment by furiousg4m3r** [comment]
I have made this translation.

![image](https://user-images.githubusercontent.com/77897370/118385744-b8eff480-b5df-11eb-83a0-1eed69f37b53.png)
