### ISSUE TITLE
[Untranslated]: Dycroft - Woodrow Doppleganger

### ISSUE THREAD

**Issue by furiousg4m3r** [furiousg4m3r/Tales-of-Destiny-DC#750]
Please describe the location and if it's Day or Night:
In Dycroft near the end of the game. Enemy name not translated.

Please paste or attach a screenshot of the issue.

Please paste or attach a screenshot of the issue.
![image](https://user-images.githubusercontent.com/77897370/116322578-54810880-a78a-11eb-931a-6bbc3eac8538.png)

**Comment by FistingUranus** [comment]
I believe this is link to the save, and that new saves with edited name will not show this in japanese

**Comment by furiousg4m3r** [comment]
Didn't get a screenshot but this has been translated.
